### ISSUE TITLE
스도쿠 구현 과정 

### ISSUE THREAD

**Issue by EunJiGil** [20-2-SKKU-OSS/2020-2-OSS-9#12]
1. 지금 숫자 안입력하거나 하면 뜨는 에러메시지는 어디서 설정한건가요?

2. 난이도 설정할때 버튼을 만들지 않고 그 부분 픽셀을 탭하면 값 리턴하고 그걸로 tap_button 하는건가여?

**Comment by EunJiGil** [comment]
에러메시지 설정안하고 자동으로 뜨는 문구인가요?

**Comment by baldwinIV** [comment]
1.코드 중
numinput("num input", "plz input number", None, minval=1, maxval=9))
라인에서 numinput 함수가 범위 밖 숫자를 입력받을시 발생하는 에러메세지입니다.
2. 
def tap_button(x, y):
    global difficulty
    result = change_pixel_index_to_button_index(x, y)
    if(result == 1):
        difficulty = 0
    elif(result == 2):
        difficulty = 1
    elif(result == 3):
        difficulty = 2

    if(difficulty != -1):
        clear()
        board_init()
        make_sudoku(0)
        erase(difficulty)
        ingame()
에서 
def change_pixel_index_to_button_index(x, y):
    if(x >= 60 and x <= 140 and y <= 0 and y >= -80):
        return 3
    elif(x >= - 40 and x <= 40 and y <= 0 and y >= -80):
        return 2
    elif(x >= - 140 and x <= -60 and y <= 0 and y >= -80):
        return 1
    else:
        return 0

change... 함수 가 x,y픽셀값따라 값을 리턴하고 tap button에서 리턴한 값에 따라 difficulty 설정을 합니다.
tap_button함수는 onscreenclick함수에 바인딩되어있기때문에, 클릭시마다 발생하는 점 참조하시면 됩니다.

**Comment by baldwinIV** [comment]
인덴테이션이 자동으로 안되었네요. 소스코드 참조해서 봐주시면 감사하겠습니다

**Comment by EunJiGil** [comment]
아 네네 네모를 클릭하지 않고 다른데 클릭해도 인풋이 가능하고 근처 네모로 들어가는 것 같아서요!
