### ISSUE TITLE
Docs 작성 역할분담

### ISSUE THREAD

**Issue by younjin0520** [20-2-SKKU-OSS/2020-2-OSS-9#13]
docs 작성조 역할분담해야 할 것 같은데 우선 저희가 할 일이 크게 wiki/read me 작성이랑 정적페이지 관리니까 들어가야 할 내용 정리해보고 하나씩 맡아서 하면 좋을 것 같아요!

**Comment by Seo-han-gyeol** [comment]
우선 게임에 대한 소개, 게임 방법은 필수적으로 들어가야 할 것 같아요

**Comment by Seo-han-gyeol** [comment]
정적페이지에는 게임 소개와 더불어 팀원 소개도 들어가면 좋을 것 같구요

**Comment by younjin0520** [comment]
넵 우선 게임 설명이랑 조작법 README에 적어놨는데 더 추가해야할 것 생각나면 그때그때 더 올리기로 해요!
