### ISSUE TITLE
발견된 버그

### ISSUE THREAD

**Issue by Seo-han-gyeol** [20-2-SKKU-OSS/2020-2-OSS-9#14]
스도쿠 게임에서 발견된 버그

1. 정수가 아닌 소수를 입력해도 소숫점을 버린 정수가 입력이 됩니다.

2. 클리어를 한 후 게임 재시작을 했을 때 종종 바로 메인 화면이 아닌 숫자가 보드 밖에 위치해 있는 이상한 화면이 나옵니다.

3. 게임 중간에 HOME 버튼을 누르면 가끔 게임을 클리어했다는 메시지가 뜹니다.

추가적으로 발견된 버그 업데이트하고 수정할 수 있으면 수정해보겠습니다.

**Comment by younjin0520** [comment]
1. 소수 입력 시 경고문 발생하게 코드 추가 했습니다.

**Comment by baldwinIV** [comment]
감사합니다
