### ISSUE TITLE
깃헙 페이지 재작성에 관하여.

### ISSUE THREAD

**Issue by baldwinIV** [20-2-SKKU-OSS/2020-2-OSS-9#2]
11-19일 기준 이번주 수업에서 팀 레포지토리에 저희가 진행할 TEAMMATES 프로젝트를 fork해야 할 것 같은데, 그렇게 되면 현재 팀 레포지토리에 저장되어 있는 깃헙 페이지를 옮겨야 할까요? 어떻게 하면 좋을지 의견 부탁드립니다.

**Comment by baldwinIV** [comment]
일단 팀 repository안에 GH-pages 브랜치를 하나 생성하였으니 앞으로 팀 블로그 post는 GH-pages의 branch안의 _post안에다가 작성해주시길 부탁드립니다.

**Comment by EunJiGil** [comment]
> 11-19일 기준 이번주 수업에서 팀 레포지토리에 저희가 진행할 TEAMMATES 프로젝트를 fork해야 할 것 같은데, 그렇게 되면 현재 팀 레포지토리에 저장되어 있는 깃헙 페이지를 옮겨야 할까요? 어떻게 하면 좋을지 의견 부탁드립니다.

그러게요 제가 fork를 하게되면 20-2-SKKU-OSS/ 에 되는 것 같은데 11조랑 2조와 같은 다른 조를 보면 팀페이지 안에 생겼더라구요 제가 maintainer가 아니라 member라서 권한이 없는것인지 한번 확인해주시겠어요?

**Comment by baldwinIV** [comment]
EunJiGil  께서 말씀해주신대로 access 권한 부여하였고, static page 수정은 GH-pages 브랜치 안에서 진행해 주시면 되겠습니다. issue close하겠습니다.
