### ISSUE TITLE
write access 

### ISSUE THREAD

**Issue by EunJiGil** [20-2-SKKU-OSS/2020-2-OSS-9#3]
discussion외에 write access가 없는 것으로 나옵니다 팀장님 확인 부탁드립니다 
" You’re making changes in a project you don’t have write access to. " 라고 나오네요 ㅠㅠ..

**Comment by baldwinIV** [comment]
WRITE ACCESS 처리 완료했습니다. ISSUE CLOSE 하겠습니다. 늦은 피드백 죄송합니다.
