### ISSUE TITLE
새로운 프로젝트 주제 선정

### ISSUE THREAD

**Issue by EunJiGil** [20-2-SKKU-OSS/2020-2-OSS-9#4]
기존에 선정했던 주제를 실사용해본 결과 기여과정에 어려움이 있어 늦기전에 기여 프로젝트를 교체하려고 합니다! 새로운 주제에 대한 의견을 여기서 나눠보면 좋을 것 같습니다

**Comment by eunji0123** [comment]
넵! 그 아까 얘기 나왔던 billboard.js가 혹시 예전에 다른 팀에서 진행했던 프로젝트 주제 맞나요??

**Comment by baldwinIV** [comment]
eunji0123~
18년 1학기에 한팀이 선정해서 기여했던 내역이 있고 정석준 학우님께서 개인 프로젝트로 조사해서 올려주신 부분도 있습니다. 링크 첨부하겠습니다.

https://github.com/18-1-SKKU-OSS/billboard.js

**Comment by June1010** [comment]
billboard.js가 최근에 아예 다른 이름으로 업그레이드? 해서 나온게 있다고 해서 봤는데, toast ui chart라는 걸로 새로 나왔다고 하네요.

**Comment by June1010** [comment]
https://github.com/nhn/tui.chart

**Comment by EunJiGil** [comment]
새로운 chart type을 제안하는 방식으로 기여하는 건가요?

**Comment by baldwinIV** [comment]
> 새로운 chart type을 제안하는 방식으로 기여하는 건가요?

https://nhn.github.io/tui.chart/latest/ 에서 현재 지원하는 차트를 확인하고 더 있다면 좋을 차트 제안, 제작 후 풀리퀘스트 혹은 docs 번역을 통해 영어에 익숙하지 않은 한국어권 웹 개발자를 지원하는 방법도 있을 것 같습니다

**Comment by eunji0123** [comment]
> > 새로운 chart type을 제안하는 방식으로 기여하는 건가요?
> 
> https://nhn.github.io/tui.chart/latest/ 에서 현재 지원하는 차트를 확인하고 더 있다면 좋을 차트 제안, 제작 후 풀리퀘스트 혹은 docs 번역을 통해 영어에 익숙하지 않은 한국어권 웹 개발자를 지원하는 방법도 있을 것 같습니다

넵 이거 좋은 것 같습니다

**Comment by EunJiGil** [comment]
이미 차트 종류가 많아서 더 제안할 종류가 있을지 걱정이긴 하네요 ..ㅠㅠ

**Comment by eunji0123** [comment]
> 이미 차트 종류가 많아서 더 제안할 종류가 있을지 걱정이긴 하네요 ..ㅠㅠ

아 저도 저 latest 화면을 지금 들어가봤는데 이 점에 동의해요 ㅠㅠ 이미 엄청 다양해서 더 기여할 수 있을지...

**Comment by EunJiGil** [comment]
사용 방법을 docs로 기여하거나 하는 방식은 좋아보이는데 Jekyll같은 것들도 보면 정적페이지로 제작하는 방법이 잘 안나와있더라구요 따로 블로그를 찾아봐야하거나 하는 느낌,, 
근데 Jekyll 테마에 기여하는건 너무 간단할려나요

**Comment by eunji0123** [comment]
> 사용 방법을 docs로 기여하거나 하는 방식은 좋아보이는데 Jekyll같은 것들도 보면 정적페이지로 제작하는 방법이 잘 안나와있더라구요 따로 블로그를 찾아봐야하거나 하는 느낌,,
> 근데 Jekyll 테마에 기여하는건 너무 간단할려나요

음.. 만약 Jekyll 테마에 기여한다고 하면 정적페이지 제작법에 대한 docs 작성 등을 얘기하시는 건가요?

**Comment by EunJiGil** [comment]
> > 사용 방법을 docs로 기여하거나 하는 방식은 좋아보이는데 Jekyll같은 것들도 보면 정적페이지로 제작하는 방법이 잘 안나와있더라구요 따로 블로그를 찾아봐야하거나 하는 느낌,,
> > 근데 Jekyll 테마에 기여하는건 너무 간단할려나요
> 
> 음.. 만약 Jekyll 테마에 기여한다고 하면 정적페이지 제작법에 대한 docs 작성 등을 얘기하시는 건가요?

네네 조금 간단할것 같기는 하네요..ㅠㅠ

**Comment by EunJiGil** [comment]
코로나 확진자 관련 프로젝트가 있으면 매일매일 정보를 업데이트해야하는 부담들을 나눠서 기여할 수 있을 것 같긴한데 잘 안나오네요

**Comment by baldwinIV** [comment]
https://github.com/grantjenks/free-python-games

파이썬 미니 게임 만들기입니다.

**Comment by eunji0123** [comment]
> https://github.com/grantjenks/free-python-games
> 
> 파이썬 미니 게임 만들기입니다.

여기 들어가봤는데 괜찮은 것 같아요!! 이슈들도 대충 훑어보니까 여기에 없는 미니 게임들 새로 제안하고 그러던데 저희도 그런 새로운 거 생각해보고 가능하면 구현도 시도해볼 수 있을 것 같아요

**Comment by June1010** [comment]
> https://github.com/grantjenks/free-python-games
> 
> 파이썬 미니 게임 만들기입니다.

저도 괜찮은 것 같아요. 아직 없는 거 제안하고 pull request 그냥 해봐도 될 거 같네요

**Comment by eunji0123** [comment]
> 코로나 확진자 관련 프로젝트가 있으면 매일매일 정보를 업데이트해야하는 부담들을 나눠서 기여할 수 있을 것 같긴한데 잘 안나오네요

그렇네요ㅠㅠ 주제가 좋은 것 같아서 저도 말씀하신 이후로 찾아봤는데 프로젝트가 있어도 거의 믿을만한 곳에서 정보를 가져오는 방식이라 저희가 크게 기여할만한 일이 없을 것 같더라구요ㅠ

**Comment by EunJiGil** [comment]
> https://github.com/grantjenks/free-python-games

오 좋은 것 같은데요?

**Comment by EunJiGil** [comment]
아 근데 제가 파이썬은 안써보긴 햇는데 괜찮겟죠........

**Comment by EunJiGil** [comment]
https://github.com/Glank/Java-Games
자바도 있긴 있네요!

**Comment by eunji0123** [comment]
> 아 근데 제가 파이썬은 안써보긴 햇는데 괜찮겟죠........

코드 작성하는 거 아니더라도 새로운 아이디어 생각하고 이슈 작성하기 등으로 기여할 수 있으니까 괜찮을 것 같아요! 그리고 저도 잘하는 입장은 아니지만.. 파이썬은 다른 언어들보단 확실히 쉬워서 보다보면 금방 하실 수 있을 것 같습니다!

**Comment by EunJiGil** [comment]
> > 아 근데 제가 파이썬은 안써보긴 햇는데 괜찮겟죠........
> 
> 코드 작성하는 거 아니더라도 새로운 아이디어 생각하고 이슈 작성하기 등으로 기여할 수 있으니까 괜찮을 것 같아요! 그리고 저도 잘하는 입장은 아니지만.. 파이썬은 다른 언어들보단 확실히 쉬워서 보다보면 금방 하실 수 있을 것 같습니다!

네네 그럼 파이썬 미니게임으로 할까요?

**Comment by eunji0123** [comment]
> 네네 그럼 파이썬 미니게임으로 할까요?

저는 좋습니다 :) 다른 분들은 어떠신가요??

**Comment by June1010** [comment]
> 네네 그럼 파이썬 미니게임으로 할까요?

저도 좋은 것 같아요

**Comment by baldwinIV** [comment]
저도 좋은 것 같아요 갑시다

**Comment by EunJiGil** [comment]
넵!! 저희 커뮤니티 활동 계획 정리

            팀원 개인별 역할 및 활동 정하기

            활동 시 이슈내용 및 고려사항 그리고 제안사항 작성 

이것도 대화 나눠볼까요

**Comment by baldwinIV** [comment]
> 넵!! 저희
> 
> 커뮤니티 활동 계획 정리
> 
> ```
>         팀원 개인별 역할 및 활동 정하기
> 
>         활동 시 이슈내용 및 고려사항 그리고 제안사항 작성
> ```
> 
> 이것도 대화 나눠볼까요

새로운 이슈 생성 필요할 것 같습니다. 여기 이슈 닫고 새 이슈 열도록 하겠습니다.
