### ISSUE TITLE
커뮤니티 선정 및 활동 계획 회의

### ISSUE THREAD

**Issue by EunJiGil** [20-2-SKKU-OSS/2020-2-OSS-9#5]
**커뮤니티 선정 및 활동 계획 회의**

**Comment by baldwinIV** [comment]
https://github.com/18-1-SKKU-OSS/2018-1-OSS-L1
과거 다른조가 했던 팀원 활동 분배 내역 잘 되있는 곳 링크 참조합니다.

**Comment by baldwinIV** [comment]
팀 스태틱 페이지 제작을 제가 해서 개인적으로 스태틱 페이지 제작 및 관리는 제가 맡고 싶습니다.

**Comment by EunJiGil** [comment]
> https://github.com/18-1-SKKU-OSS/2018-1-OSS-L1
> 과거 다른조가 했던 팀원 활동 분배 내역 잘 되있는 곳 링크 참조합니다.

오 정말 세세하게 잘되어있네요

**Comment by EunJiGil** [comment]
> 팀 스태틱 페이지 제작을 제가 해서 개인적으로 스태틱 페이지 제작 및 관리는 제가 맡고 싶습니다.

네네 근데 저 깃허브 보니 4명 다같이 한 것 같아서 스태틱페이지가 관리하는 중점이고 하다보니 다같이하는게 좋지 않을까요?

**Comment by EunJiGil** [comment]
좀 더 세분화해서요! 멤버페이지를 한명이 관리하고, 각 프로젝트 별 commit을 시간 순서대로 정리하는걸 한명이하고, 번역페이지를 한명이하고 이런식으루요!

**Comment by eunji0123** [comment]
> 좀 더 세분화해서요! 멤버페이지를 한명이 관리하고, 각 프로젝트 별 commit을 시간 순서대로 정리하는걸 한명이하고, 번역페이지를 한명이하고 이런식으루요!

저도 이게 괜찮은 것 같습니다! 저 다른 팀 예시처럼 디테일한 부분부분은 팀원들이 나눠서 맡고 상훈님은 거기에 더해서 static page 최초 생성, 테마 적용, 전체적인 관리 등을 개인 역할로 기록하셔도 좋을 것 같아요!

**Comment by EunJiGil** [comment]
> > 좀 더 세분화해서요! 멤버페이지를 한명이 관리하고, 각 프로젝트 별 commit을 시간 순서대로 정리하는걸 한명이하고, 번역페이지를 한명이하고 이런식으루요!
> 
> 저도 이게 괜찮은 것 같습니다! 저 다른 팀 예시처럼 디테일한 부분부분은 팀원들이 나눠서 맡고 상훈님은 거기에 더해서 static page 최초 생성, 테마 적용, 전체적인 관리 등을 개인 역할로 기록하셔도 좋을 것 같아요!

네네 좋은 것 같아요! 그리고 18-1-SKKU-OSS 보니 그냥 https://github.com/18-1-SKKU-OSS 에다가 하고자하는 프로젝트 fork해서 하신것같네요

**Comment by EunJiGil** [comment]
**1. 저희 커뮤니티는 깃헙 이슈페이지로 하는 것으로 할까요?
2. 활동 시 이슈내용 및 고려사항 그리고 제안사항은 어떤게 있을까요?**

**Comment by baldwinIV** [comment]
> > > 좀 더 세분화해서요! 멤버페이지를 한명이 관리하고, 각 프로젝트 별 commit을 시간 순서대로 정리하는걸 한명이하고, 번역페이지를 한명이하고 이런식으루요!
> > 
> > 
> > 저도 이게 괜찮은 것 같습니다! 저 다른 팀 예시처럼 디테일한 부분부분은 팀원들이 나눠서 맡고 상훈님은 거기에 더해서 static page 최초 생성, 테마 적용, 전체적인 관리 등을 개인 역할로 기록하셔도 좋을 것 같아요!
> 
> 네네 좋은 것 같아요! 그리고 18-1-SKKU-OSS 보니 그냥 https://github.com/18-1-SKKU-OSS 에다가 하고자하는 프로젝트 fork해서 하신것같네요

저희도 저희 파이썬 미니 게임 프로젝트 포크하고 거기에 pullrequest 브랜치 하나 만들어서 작업하는 것이 좋다고 생각합니다. (main 브랜치는 원본으로 유지)

**Comment by EunJiGil** [comment]
> > > > 좀 더 세분화해서요! 멤버페이지를 한명이 관리하고, 각 프로젝트 별 commit을 시간 순서대로 정리하는걸 한명이하고, 번역페이지를 한명이하고 이런식으루요!
> > > 
> > > 
> > > 저도 이게 괜찮은 것 같습니다! 저 다른 팀 예시처럼 디테일한 부분부분은 팀원들이 나눠서 맡고 상훈님은 거기에 더해서 static page 최초 생성, 테마 적용, 전체적인 관리 등을 개인 역할로 기록하셔도 좋을 것 같아요!
> > 
> > 
> > 네네 좋은 것 같아요! 그리고 18-1-SKKU-OSS 보니 그냥 https://github.com/18-1-SKKU-OSS 에다가 하고자하는 프로젝트 fork해서 하신것같네요
> 
> 저희도 저희 파이썬 미니 게임 프로젝트 포크하고 거기에 pullrequest 브랜치 하나 만들어서 작업하는 것이 좋다고 생각합니다. (main 브랜치는 원본으로 유지)

네네 포크 완료했습니다! https://github.com/20-2-SKKU-OSS/free-python-games

**Comment by eunji0123** [comment]
1. 네 저는 좋습니다!
2. 약간 뭘 써야할지 감이 안 오는데.. "모든 회의, 질문 등은 팀 repository의 이슈페이지에 남겨서 기록하기" 등을 적으면 되는 걸까요..?

**Comment by baldwinIV** [comment]
> **1. 저희 커뮤니티는 깃헙 이슈페이지로 하는 것으로 할까요? 2. 활동 시 이슈내용 및 고려사항 그리고 제안사항은 어떤게 있을까요?**

1, 좋습니다. 현재 커뮤니티 기능 아주 잘 수행되고 있는 것 같아요.

2. 

무료 파이썬 게임은 교육과 재미를위한 무료 파이썬 게임의 Apache2 라이센스 컬렉션입니다. 게임은 간단한 파이썬 코드로 작성되고 실험 및 변경을 위해 설계되었습니다. 여러 고전적인 아케이드 게임의 단순화 된 버전이 포함되어 있습니다.

파이썬은 세계에서 가장 인기있는 5 개 프로그래밍 언어 중 하나이며 Python.org무료로 사용할 수 있습니다. 파이썬에는 설치와 함께 배포된 광범위한 표준 라이브러리가 포함되어 있습니다. 스탠다드 라이브러리에는 아이들에게 프로그래밍을 소개하는 인기있는 방법인 거북이라는 모듈이 있습니다. 거북이는 1966년 월리 퍼지그와 시모어 페이퍼트가 개발한 오리지널 로고 프로그래밍 언어의 일부였습니다. 무료 파이썬 게임의 모든 게임은 파이썬과 거북이 모듈을 사용하여 구현됩니다.

2012년부터 프리 파이썬 게임은 방과 후 프로그램으로 시작하여 도심 청소년들에게 프로그래밍을 가르쳤습니다. 목표는 배우는 것만큼 이나 재미있게 하는 것이었습니다. 그 이후로 게임은 교실에서 여름 날 캠프에 이르기까지 다양한 설정에서 개선되고 사용되었습니다.

게임은 윈도우를 실행하는 데스크톱 컴퓨터를 포함 어디서나 파이썬을 실행, 맥 OS, 또는 리눅스와 라즈베리 파이와 같은 이전 또는 저전력 하드웨어를 포함. 6~12학년 미국 전역의 어린이들은 게임을 통해 암호화 및 투사체 모션과 같은 주제에 대해 배우는 것을 즐겼습니다.

각 게임은 다른 게임과 완전히 독립적이며 학생들과 함께 작업 할 수있는 연습 목록과 함께 의견을 포함합니다. 창의력과 유연성이 중요합니다. 새로운 기능이나 동작을 구현하는 옳고 그인의 방법은 없습니다! 학생이 어떤 게임에 참여할지 알 수 없습니다.

소개글의 한글 번역본입니다. 이 글을 읽어보면 이 프로젝트가 미국에서 파이썬을 배우는 학생들에게 프로그래밍에 호기심을 가질 수 있도록 하는데 의의가 있는 것 같습니다. 

그렇다면 저희는 게임을 하나 정하여 다같이 만드는데, 게임 안에 구현된 파이썬의 기초적인 기능들 혹은 간단한 논리 구조등을 docs화 하여 완전 초보 학생들에게 도움이 되게 하는 tutorial 을 만들어 기여해보는건 어떨까요?

**Comment by EunJiGil** [comment]
> 1. 네 저는 좋습니다!
> 2. 약간 뭘 써야할지 감이 안 오는데.. "모든 회의, 질문 등은 팀 repository의 이슈페이지에 남겨서 기록하기" 등을 적으면 되는 걸까요..?

네네 2번에 그런걸 적는 것 같아요! 스태틱 페이지에는 매주 포스팅을 한다, 질문사항이 있을때는 이슈페이지를 활용한다, 최소한 일주일에 한번은 커밋한다 이런것....?

**Comment by EunJiGil** [comment]
> > **1. 저희 커뮤니티는 깃헙 이슈페이지로 하는 것으로 할까요? 2. 활동 시 이슈내용 및 고려사항 그리고 제안사항은 어떤게 있을까요?**
> 
> 1, 좋습니다. 현재 커뮤니티 기능 아주 잘 수행되고 있는 것 같아요.
> 
> 
> _무료 파이썬 게임은 교육과 재미를위한 무료 파이썬 게임의 Apache2 라이센스 컬렉션입니다. 게임은 간단한 파이썬 코드로 작성되고 실험 및 변경을 위해 설계되었습니다. 여러 고전적인 아케이드 게임의 단순화 된 버전이 포함되어 있습니다.
> 
> 파이썬은 세계에서 가장 인기있는 5 개 프로그래밍 언어 중 하나이며 Python.org무료로 사용할 수 있습니다. 파이썬에는 설치와 함께 배포된 광범위한 표준 라이브러리가 포함되어 있습니다. 스탠다드 라이브러리에는 아이들에게 프로그래밍을 소개하는 인기있는 방법인 거북이라는 모듈이 있습니다. 거북이는 1966년 월리 퍼지그와 시모어 페이퍼트가 개발한 오리지널 로고 프로그래밍 언어의 일부였습니다. 무료 파이썬 게임의 모든 게임은 파이썬과 거북이 모듈을 사용하여 구현됩니다.
> 
> 2012년부터 프리 파이썬 게임은 방과 후 프로그램으로 시작하여 도심 청소년들에게 프로그래밍을 가르쳤습니다. 목표는 배우는 것만큼 이나 재미있게 하는 것이었습니다. 그 이후로 게임은 교실에서 여름 날 캠프에 이르기까지 다양한 설정에서 개선되고 사용되었습니다.
> 
> 게임은 윈도우를 실행하는 데스크톱 컴퓨터를 포함 어디서나 파이썬을 실행, 맥 OS, 또는 리눅스와 라즈베리 파이와 같은 이전 또는 저전력 하드웨어를 포함. 6~12학년 미국 전역의 어린이들은 게임을 통해 암호화 및 투사체 모션과 같은 주제에 대해 배우는 것을 즐겼습니다.
> 
> 각 게임은 다른 게임과 완전히 독립적이며 학생들과 함께 작업 할 수있는 연습 목록과 함께 의견을 포함합니다. 창의력과 유연성이 중요합니다. 새로운 기능이나 동작을 구현하는 옳고 그인의 방법은 없습니다! 학생이 어떤 게임에 참여할지 알 수 없습니다._
> 
> 소개글의 한글 번역본입니다. 이 글을 읽어보면 이 프로젝트가 미국에서 파이썬을 배우는 학생들에게 프로그래밍에 호기심을 가질 수 있도록 하는데 의의가 있는 것 같습니다.
> 
> 그렇다면 저희는 게임을 하나 정하여 다같이 만드는데, 게임 안에 구현된 파이썬의 기초적인 기능들 혹은 간단한 논리 구조등을 docs화 하여 완전 초보 학생들에게 도움이 되게 하는 tutorial 을 만들어 기여해보는건 어떨까요?

**"저희는 게임을 하나 정하여 다같이 만드는데, 게임 안에 구현된 파이썬의 기초적인 기능들 혹은 간단한 논리 구조등을 docs화 하여 완전 초보 학생들에게 도움이 되게 하는 tutorial 을 만들어 기여해보는건 어떨까요? "**
-> 이부분 좋은 것 같아요 저희의 주 기여내용을 이걸로 정하고 이제 분배해서 '팀원 개인별 역할 및 활동 정하기' 정하면 될 것 같습니다

**Comment by eunji0123** [comment]
> 그렇다면 저희는 게임을 하나 정하여 다같이 만드는데, 게임 안에 구현된 파이썬의 기초적인 기능들 혹은 간단한 논리 구조등을 docs화 하여 완전 초보 학생들에게 도움이 되게 하는 tutorial 을 만들어 기여해보는건 어떨까요?

저도 이 부분 매우 좋은 것 같습니다. 실제로 저 원래 프로젝트에 추가되지 않더라도 저희가 이런 걸 만들어보고 시도했다는 게 의미가 클 것 같아요! 그리고 각자 게임의 세부 기능들을 맡아서 구현해보거나 docs화 작업에 참여하거나 하는 식으로 역할 분배도 가능할 것 같습니다

**Comment by EunJiGil** [comment]
> > **1. 저희 커뮤니티는 깃헙 이슈페이지로 하는 것으로 할까요? 2. 활동 시 이슈내용 및 고려사항 그리고 제안사항은 어떤게 있을까요?**
> 
> 1, 좋습니다. 현재 커뮤니티 기능 아주 잘 수행되고 있는 것 같아요.
> 
> 
> _무료 파이썬 게임은 교육과 재미를위한 무료 파이썬 게임의 Apache2 라이센스 컬렉션입니다. 게임은 간단한 파이썬 코드로 작성되고 실험 및 변경을 위해 설계되었습니다. 여러 고전적인 아케이드 게임의 단순화 된 버전이 포함되어 있습니다.
> 
> 파이썬은 세계에서 가장 인기있는 5 개 프로그래밍 언어 중 하나이며 Python.org무료로 사용할 수 있습니다. 파이썬에는 설치와 함께 배포된 광범위한 표준 라이브러리가 포함되어 있습니다. 스탠다드 라이브러리에는 아이들에게 프로그래밍을 소개하는 인기있는 방법인 거북이라는 모듈이 있습니다. 거북이는 1966년 월리 퍼지그와 시모어 페이퍼트가 개발한 오리지널 로고 프로그래밍 언어의 일부였습니다. 무료 파이썬 게임의 모든 게임은 파이썬과 거북이 모듈을 사용하여 구현됩니다.
> 
> 2012년부터 프리 파이썬 게임은 방과 후 프로그램으로 시작하여 도심 청소년들에게 프로그래밍을 가르쳤습니다. 목표는 배우는 것만큼 이나 재미있게 하는 것이었습니다. 그 이후로 게임은 교실에서 여름 날 캠프에 이르기까지 다양한 설정에서 개선되고 사용되었습니다.
> 
> 게임은 윈도우를 실행하는 데스크톱 컴퓨터를 포함 어디서나 파이썬을 실행, 맥 OS, 또는 리눅스와 라즈베리 파이와 같은 이전 또는 저전력 하드웨어를 포함. 6~12학년 미국 전역의 어린이들은 게임을 통해 암호화 및 투사체 모션과 같은 주제에 대해 배우는 것을 즐겼습니다.
> 
> 각 게임은 다른 게임과 완전히 독립적이며 학생들과 함께 작업 할 수있는 연습 목록과 함께 의견을 포함합니다. 창의력과 유연성이 중요합니다. 새로운 기능이나 동작을 구현하는 옳고 그인의 방법은 없습니다! 학생이 어떤 게임에 참여할지 알 수 없습니다._
> 
> 소개글의 한글 번역본입니다. 이 글을 읽어보면 이 프로젝트가 미국에서 파이썬을 배우는 학생들에게 프로그래밍에 호기심을 가질 수 있도록 하는데 의의가 있는 것 같습니다.
> 
> 그렇다면 저희는 게임을 하나 정하여 다같이 만드는데, 게임 안에 구현된 파이썬의 기초적인 기능들 혹은 간단한 논리 구조등을 docs화 하여 완전 초보 학생들에게 도움이 되게 하는 tutorial 을 만들어 기여해보는건 어떨까요?

고려사항에 

" README.rd를 읽어보면 이 프로젝트가 미국에서 파이썬을 배우는 학생들에게 프로그래밍에 호기심을 가질 수 있도록 하는데 의의가 있다는 것을 알 수 있는데 이를 고려해서 프로젝트를 진행해야 한다. " 

도 넣을 수 있겠네요!

**Comment by baldwinIV** [comment]
전체 필요해 보이는 역할 (추가 부탁드립니다.)

1. 커뮤니티에 피력된 의견 정리하여 static page에 정리
2. 게임 기획과 개발
3. 개발된 게임에 대한 교육문서 doc 제작
4. 팀의 전체적인 작업 흐름을 이끌고 전체적인 commit을 수정하는 역할(커밋 관리자)
5. static page에 팀원 소개와 프로젝트 소개 마저 끝내기

**Comment by baldwinIV** [comment]
> 전체 필요해 보이는 역할 (추가 부탁드립니다.)
> 
> 1. 커뮤니티에 피력된 의견 정리하여 static page에 정리 (타임라인 사용)
> 2. 게임 기획과 개발
> 3. 개발된 게임에 대한 교육문서 doc 제작
> 4. 팀의 전체적인 작업 흐름을 이끌고 전체적인 commit을 수정하는 역할(커밋 관리자)
> 5. static page에 팀원 소개와 프로젝트 소개 마저 끝내기

이건 따로 이슈 하나 더 파겠습니다

**Comment by EunJiGil** [comment]
네네 은지님 열심히 해주셨는데 은지님도 이슈하나 파시는 건 어떤가요 ,,ㅎ 그래도 이슈파면 이름 남길 수 있으니까요!
팔 주제가 어떤게 있징

**Comment by eunji0123** [comment]
> 네네 은지님 열심히 해주셨는데 은지님도 이슈하나 파시는 건 어떤가요 ,,ㅎ 그래도 이슈파면 이름 남길 수 있으니까요!
> 팔 주제가 어떤게 있징

ㅋㅋ 감사합니당 이제야 봤어요ㅠㅠ 팀에 도움될 거 생각나면 시도해볼게요!
