### ISSUE TITLE
필요한 역할들(추가 부탁드립니다.)

### ISSUE THREAD

**Issue by baldwinIV** [20-2-SKKU-OSS/2020-2-OSS-9#6]
1.커뮤니티에 피력된 의견 정리하여 static page에 정리 (타임라인 사용)
2.게임 기획과 개발
3.개발된 게임에 대한 교육문서 doc 제작
4.팀의 전체적인 작업 흐름을 이끌고 전체적인 commit을 수정하는 역할(커밋 관리자)
5.static page에 팀원 소개와 프로젝트 소개 마저 끝내기

**Comment by eunji0123** [comment]
- static page에 우리가 개발하는 게임에 대한 소개, 기능 등을 설명하는 포스트? 내용? 정리

**Comment by EunJiGil** [comment]
근데 이게임 어떤가요
https://www.youtube.com/watch?v=-e_5sOsKqrU
코드도 다 있더라구요 ㅋㅋㅋㅋ
일단 확인하시면 삭제할게요 ㅋㅋㅎ

**Comment by EunJiGil** [comment]
저거 아니더라도 파이썬 미니게임 소스코드들은 깃헙에 많으려나요

**Comment by eunji0123** [comment]
> 근데 이게임 어떤가요
> https://www.youtube.com/watch?v=-e_5sOsKqrU
> 코드도 다 있더라구요 ㅋㅋㅋㅋ
> 일단 확인하시면 삭제할게요 ㅋㅋㅎ

오 처음에 제가 생각했던 것보다도 뭔가 있어보이는 게임이에요.. ㅋㅋ 도움이 될만한 파이썬 게임 소스코드들은 꽤 있을 것 같아서 아예 게임 좀 여러개 만들어도 괜찮을 것 같아요! 쉬운 건 저희끼리 해보고 어려운 건 다른 거 참고해보고..ㅎㅎ

**Comment by EunJiGil** [comment]
네네 좋습니다 ! 
- 게임 버그 수정, 기능 추가 
등도 있을 것 같아요

**Comment by baldwinIV** [comment]
파이썬 게임 배우는데 도움이 될 것 같습니다. 
저는 처음에 간단하게 스도쿠 만들어보는것도 나쁘지 않을것 같아요

**Comment by eunji0123** [comment]
그리구 제 개인적인 생각으로는, 그 깃헙에 Projects 부분은 본인이 맡은 프로젝트는 본인이 생성하고 관리(개발목록 작성, 개발완료 등)하는 게 나을 것 같은데 어떻게 생각하시나요??

**Comment by eunji0123** [comment]
> 저는 처음에 간단하게 스도쿠 만들어보는것도 나쁘지 않을것 같아요

스도쿠도 좋네요!

**Comment by EunJiGil** [comment]
> 그리구 제 개인적인 생각으로는, 그 깃헙에 Projects 부분은 본인이 맡은 프로젝트는 본인이 생성하고 관리(개발목록 작성, 개발완료 등)하는 게 나을 것 같은데 어떻게 생각하시나요??

네네 좋아요!

**Comment by EunJiGil** [comment]
혹시 다들 이번 과제 정적페이지 만드셧나요? config.yml 수정 내용 질문드려도 되나요 계속 pages not found 오류가 떠서 ....

**Comment by eunji0123** [comment]
저도 지금 하고 있어서 ㅠㅠㅠ 근데 저번주에 처음으로 만들때 교수님께서 보여주신 테마 말고 다른 거 몇 번 시도했었는데 왜인지 다 오류가 떠서 결국 교수님께서 보여주셨던 거 그대로 했었어요..

**Comment by EunJiGil** [comment]
> 저도 지금 하고 있어서 ㅠㅠㅠ 근데 저번주에 처음으로 만들때 교수님께서 보여주신 테마 말고 다른 거 몇 번 시도했었는데 왜인지 다 오류가 떠서 결국 교수님께서 보여주셨던 거 그대로 했었어요..

그춐ㅋㅋㅋㅋㅋ저도.......... https://eunjigil.github.io/eunjigil2.github.io/ 이렇게 떠버려서... 
상훈님 하셧나요.......................

**Comment by eunji0123** [comment]
맞아요맞아요 저도 지금 은지님 페이지처럼 그런 식으로 뜬 거 많았어요 ㅋ큐ㅠㅠㅠ 이게 그 페이지를 온전히 구현하려면 다른 부분도 복붙해와야해서 그러는 건지ㅠㅠㅠ

**Comment by EunJiGil** [comment]
> 맞아요맞아요 저도 지금 은지님 페이지처럼 그런 식으로 뜬 거 많았어요 ㅋ큐ㅠㅠㅠ 이게 그 페이지를 온전히 구현하려면 다른 부분도 복붙해와야해서 그러는 건지ㅠㅠㅠ

저 다른 부분 다 복붙한것도 해봤는데 안되더라구요 ,,ㅠㅠ @baldwinIV 도와주세요 ...................

**Comment by baldwinIV** [comment]
저는 테마 README에서 시키는 대로 해봤는데 테마 적용이 정상적으로 안되네요. 지킬 서버가 터졌나 싶은데요. 잘 모르겠습니다

**Comment by baldwinIV** [comment]
Your site is having problems building: Your site is using the relative_permalinks configuration option. This setting is deprecated as has been removed from the latest version of Jekyll. To ensure your site continues to build as expected, remove the option from your site's configuration and update any post or page permalinks to be absolute to the site root, not the parent folder. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#relative-permalinks-configured.

레포지토리 옵션가서 제대로 사이트가 빌드되고 있는지 확인들 해보세요

**Comment by June1010** [comment]
- 게임 실사용 후 버그 제보 및 보완
- 새로운 게임 제안
- 개발된 게임에 대한 문서 작성

**Comment by younjin0520** [comment]
개발된 게임에 대한 문서 작성 부분을 가장 먼저 해야될 것 같고 거기에 실사용 후 버그 제보 및 보완 내용도 포함되면 좋을 것 같습니다!

**Comment by Seo-han-gyeol** [comment]
게임을 해보고 분명 불편한 UI같은것들도 있을건데, 그 부분에 대한 개선도 좋아보이네요
