### ISSUE TITLE
지킬 relative_permalinks 지원 관련 테마 선택 해결 방안

### ISSUE THREAD

**Issue by baldwinIV** [20-2-SKKU-OSS/2020-2-OSS-9#7]
Your site is having problems building: Your site is using the relative_permalinks configuration option. This setting is deprecated as has been removed from the latest version of Jekyll. To ensure your site continues to build as expected, remove the option from your site's configuration and update any post or page permalinks to be absolute to the site root, not the parent folder. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#relative-permalinks-configured.

 개인 정적 페이지 하고 나서 테마 적용이 제대로 안되었습니다.  깃헙 페이지 링크는 제대로 만들어져서 접속은 되고 내용은 보이는데 테마는 적용이 안되어 있더라고요.
 위 메세지는 그 때 repository의 settings에 github page 란에 있던 메세지 입니다. 더이상 지킬에서 relative_permalinks를  지원하지 않으니 너의 config를 업데이트하라는 내용이었습니다.
 그 후 제가 적용하려던 테마의 마지막 커밋 날짜를 보니 5년전이었습니다. 더 이상 관리가 안되는 테마를 적용하려고 해서 최신 변경사항이 적용이 안되었나 봅니다.

sol
1. 지킬 테마를 찾아다니는데 단 _config.yml이 최근 5일정도 안에 수정된 테마를 찾는다.
2. 거기 readme.md 보고 따라한다.

정도가 되겠습니다.
다들 건승하시고 프로젝트 화이팅 해보죠

**Comment by EunJiGil** [comment]
감사합니다!! 말씀해주신대로 해봤는데 안되는 이유는 뭘까요 하핳..ㅠㅠㅠㅠ
따라한 다음에 링크에 뜨기까지 얼마정도 기다리셧나요?

**Comment by EunJiGil** [comment]
와 됐습니다......감사해요 ㅠㅠㅠㅠㅠㅠㅠㅠ..........
