### ISSUE TITLE
게임 선정 및 개발 계획 

### ISSUE THREAD

**Issue by EunJiGil** [20-2-SKKU-OSS/2020-2-OSS-9#8]
파이썬 미니 게임을 하나 선정해서 개발 계획을 세워보면 좋을 것 같습니다!

**Comment by younjin0520** [comment]
제 생각에는 우선 다들 이번주내로 기한정해서 전체적인 게임 사용해보고 코드 살펴보고 어떤 식으로 개발할지 (ex. 기존 게임 개선 방안, 새 게임 개발, 코드 수정 등) 의견나누는게 좋을 것 같습니다 :)

**Comment by EunJiGil** [comment]
아 네네 그방식도 좋은데 팀원 모두가 같은 코드 살펴보고 개선 방안을 찾기에 좀 오래걸릴거같아서 지금 있는 게임들에 아예 새로운 미니게임을 추가하는 방향으로 같이 개발해서 커밋하는게 더 나을 것 같습니다 아니면 몇명은 기존 게임 코드수정으로하고 몇명은 개발로 해도 될것같구요
 게임 기획과 개발 or 원하는 사람 기존 게임 코드 수정 -> 개발된 게임에 대한 교육문서 doc 제작 / 수정된 게임에 대한 교육문서 doc제작 -> static page에 게임 설명 순서로 하면 될것같아요

**Comment by EunJiGil** [comment]
1. 게임 기획과 개발 or 2. 기존 게임 코드 수정에 원하는 부분 팀원분들이 코멘트 달아주시면  팀나누면 될 것 같습니다

**Comment by June1010** [comment]
상훈님이 말씀하셨던 스도쿠나 테트리스 등등 고전 게임중에서 몇가지 고르면 좋을 것 같아요

**Comment by eunji0123** [comment]
아니면 hangman 같은 게임도 괜찮을 것 같아요

**Comment by EunJiGil** [comment]
테트리스랑 Hangman with AI 두개 
free-python-games 프로젝트 이슈에 이미 있더라구요 ㅠㅠ

**Comment by younjin0520** [comment]
미국학생들 대상이니까 한국전통놀이로 개발하는거 어떤가요? 윷놀이같은거요. 한국 놀이도 알릴 수 있고 미국에선 생소하니까 재밌게 할 수 있을것같습니다.

**Comment by eunji0123** [comment]
> 테트리스랑 Hangman with AI 두개
> free-python-games 프로젝트 이슈에 이미 있더라구요 ㅠㅠ

앗 그렇군요 ㅠㅠ

**Comment by eunji0123** [comment]
> 미국학생들 대상이니까 한국전통놀이로 개발하는거 어떤가요? 윷놀이같은거요. 한국 놀이도 알릴 수 있고 미국에선 생소하니까 재밌게 할 수 있을것같습니다.

이것도 좋은 아이디어긴 한데 만약에 다 만들고 나서 저 원래 free python games에 pull request를 한다고 하면, 너무 우리만 아는 게임이라 좀 그럴 것 같기도 해요.. ㅋ큐ㅠㅠ

**Comment by EunJiGil** [comment]
오늘 8시에 보이스톡 회의로 대체합니다!
