### ISSUE TITLE
정적 페이지 적용문제

### ISSUE THREAD

**Issue by EunJiGil** [20-2-SKKU-OSS/2020-2-OSS-9#9]
팀장님 정적 페이지 index.html이나 포스트 적용안되는 것 같은데 
저번처럼 5일 이내로 된 템플릿으로 바꿔야 될까요

**Comment by baldwinIV** [comment]
지금 확인하겠습니다

**Comment by baldwinIV** [comment]
저희 팀 페이지 말씀하시는거면 main 브랜치가 아니라 GH-pages 브랜치에 수정사항 기입해주셔야 합니다.

**Comment by baldwinIV** [comment]
![image](https://user-images.githubusercontent.com/60903175/100411698-d7a41280-30b5-11eb-878b-63e49119e3ba.png)

**Comment by EunJiGil** [comment]
아 ...... 그렇군요ㅎㅎ 메인에다가 수정했네요

**Comment by EunJiGil** [comment]
감사합니다!
